<a href="https://colab.research.google.com/github/bannu053/Data_Science/blob/main/Pandas/Assignments/Netflix_Insights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("cleaned__netflix.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,no_of_genres,primary_genre,duration_int,type_flag,cast_count,content_age
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",1,Documentaries,90,0,0,6
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",3,International TV Shows,2,1,19,5
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,3,Crime TV Shows,1,1,9,5
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2,Docuseries,1,1,0,5
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,3,International TV Shows,2,1,8,5

In [5]:
# How many total rows and columns are there?
df.shape

(8807, 18)

In [6]:
# What are the column names?
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'no_of_genres', 'primary_genre', 'duration_int', 'type_flag',
       'cast_count', 'content_age'],
      dtype='object')

In [7]:
# How many missing values in each column?
df.isnull().sum()

show_id             0
type                0
title               0
director         2634
cast              825
country           831
date_added         10
release_year        0
rating              4
duration            3
listed_in           0
description         0
no_of_genres        0
primary_genre       0
duration_int        0
type_flag           0
cast_count          0
content_age         0
dtype: int64

In [9]:
# What are the unique values in "type"?
df['type'].unique()

array(['Movie', 'TV Show'], dtype=object)

In [10]:
# Count how many Movies vs TV Shows
df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [15]:
# How many shows are from India?
df[df['country']=="India"]['country'].value_counts()

country
India    972
Name: count, dtype: int64

In [18]:
# Which year has the highest number of releases?
df['release_year'].value_counts().head(1)

release_year
2018    1147
Name: count, dtype: int64

In [19]:
# Most common rating (TV-MA, PG, etc.)
df['rating'].value_counts().head(1)

rating
TV-MA    3207
Name: count, dtype: int64

In [21]:
# Find all shows that contain “Love” in title
df[df['title'].str.contains("Love")]['title']

25                Love on the Spectrum
158            Love Don't Cost a Thing
159                     Love in a Puff
206          LSD: Love, Sex Aur Dhokha
227                        Really Love
                     ...
8567    The Year of Happiness and Love
8575                   This Is My Love
8649             Two Lovers and a Bear
8721                     What Is Love?
8725              What's Up With Love?
Name: title, Length: 188, dtype: object

In [24]:
# Count how many titles contain numbers
df['title'].str.contains(r"\d").value_counts()

title
False    8324
True      483
Name: count, dtype: int64

In [32]:
# Find longest movie title
max_len = df['title'].str.len().max()
df[df['title'].str.len() == max_len]['title']

5164    Jim & Andy: The Great Beyond - Featuring a Ver...
Name: title, dtype: object